### USER DATA
GET http://localhost:80/api/user?uid=kun4zXFlM7g8JOubr2nbBkoo0lD2

### SRD ITEM
GET http://localhost:80/api/items/675

### SRD ITEMS
GET http://localhost:80/api/items

### SRD WEAPONS
GET http://localhost:80/api/items?type=weapon

### SRD ARMOR
GET http://localhost:80/api/items?type=armor

### SRD SPELL
GET http://localhost:80/api/spells/164

### SRD SPELL LIST (QUERY OPTIONAL)
http://localhost:80/api/spells?class=wizard&level=3&school=divination

### SRD RACE LIST
http://localhost:80/api/races

### SRD RACE BY ID
http://localhost:80/api/races/5

### SRD BACKGROUND LIST
http://localhost:80/api/bg

### SRD BACKGROUND BY ID
http://localhost:80/api/bg/5

### SRD CLASS LIST
http://localhost:80/api/classes

### SRD CLASS BY ID
http://localhost:80/api/classes/10

### SRD FEAT LIST (QUERY OPTIONAL)
http://localhost:80/api/feats?class=fighter&subclass=eldritch+knight&level=10

### SRD FEAT BY ID
http://localhost:80/api/feats/5

### GET CHARACTER
GET http://localhost:80/api/data/pc/889ad4f2-9305-4a26-87d2-d110b2ff289a?detail=true
Authorization: dev wkgreen13@gmail.com

### GET ALL CHARACTERS
GET http://localhost:80/api/data/pc?detail=true
Authorization: dev wkgreen13@gmail.com

### SEARCH CHARACTERS
GET http://localhost:80/api/data/pc?name=sam&detail=true
Authorization: dev wkgreen13@gmail.com

### REQUEST AUTH TO CHARACTER
POST http://localhost:80/api/data/pc/889ad4f2-9305-4a26-87d2-d110b2ff289a/auth
Authorization: dev clayton.yarborough@gmail.com

### INVITE CHARACTER TO PARTY
POST http://localhost:80/api/data/pc/889ad4f2-9305-4a26-87d2-d110b2ff289a/invite?party=510996a9-bb48-4e32-b45f-ee0a696b5853
Authorization: dev clayton.yarborough@gmail.com

### DELETE CHARACTER
DELETE http://localhost:80/api/data/pc/dda66e3e-9fd9-4582-a4be-acb1f973f090
Authorization: dev wkgreen13@gmail.com

### UPSERT CHARACTER
POST http://localhost:80/api/data/pc
Content-Type: application/json
Authorization: dev wkgreen13@gmail.com

{
  "name": "Carpenter Tim",
  "authUsers": ["kDBRAhqohWPymd7249ZiQ4i9T153"],
  "raceID": 4,
  "classID": 10,
  "backgroundID": 5,
  "stats": {
    "str": 10,
    "dex": 15,
    "con": 13,
    "int": 13,
    "wis": 8,
    "cha": 16
  },
  "xp": 300,
  "hp": 8,
  "maxHP": 8,
  "proTools": [
    "Poisoner's Tools"
  ],
  "proWeapons": [
    "Dagger",
    "Dart",
    "Sling",
    "Quarterstaff",
    "Crossbow, light"
  ],
  "languages": [
    "Common",
    "Infernal",
    "Orc",
    "Draconic"
  ],
  "equipmentIDs": [
    31
  ],
  "weaponIDs": [
    17,
    37
  ],
  "inventory": [
    {
      "id": 14,
      "qty": 20
    }
  ],
  "gold": 10,
  "spellIDs": [
    46,
    37
  ]
}

### UPSERT PARTY
POST http://localhost:80/api/data/party
Content-Type: application/json
Authorization: dev wkgreen13@gmail.com

{
  "name": "New Beginnings",
  "photoURL": "https://cdn.discordapp.com/attachments/524229046226255882/668206434080784436/unknown.png"
}

### GET PARTY
GET http://localhost:80/api/data/party/510996a9-bb48-4e32-b45f-ee0a696b5853
Authorization: dev wkgreen13@gmail.com

### GET PARTIES FOR USER (ADMIN)
GET http://localhost:80/api/data/party
Authorization: dev wkgreen13@gmail.com

### DELETE PARTY
DELETE http://localhost:80/api/data/party/510996a9-bb48-4e32-b45f-ee0a696b5853
Authorization: dev wkgreen13@gmail.com

### JOIN PARTY
POST http://localhost:80/api/data/party/510996a9-bb48-4e32-b45f-ee0a696b5853/join?member=889ad4f2-9305-4a26-87d2-d110b2ff289a
Authorization: dev wkgreen13@gmail.com

### KICK FROM PARTY
POST http://localhost:80/api/data/party/510996a9-bb48-4e32-b45f-ee0a696b5853/kick?member=889ad4f2-9305-4a26-87d2-d110b2ff289a
Authorization: dev wkgreen13@gmail.com
