### SRD ITEM
GET http://localhost:80/api/items/675

### SRD ITEMS
GET http://localhost:80/api/items

### SRD WEAPONS
GET http://localhost:80/api/items?type=weapon

### SRD ARMOR
GET http://localhost:80/api/items?type=armor

### SRD SPELL
GET http://localhost:80/api/spells/164

### SRD SPELL LIST (QUERY OPTIONAL)
http://localhost:80/api/spells?class=wizard&level=3&school=divination

### SRD RACE LIST
http://localhost:80/api/races

### SRD RACE BY ID
http://localhost:80/api/races/5

### SRD BACKGROUND LIST
http://localhost:80/api/bg

### SRD BACKGROUND BY ID
http://localhost:80/api/bg/5

### SRD CLASS LIST
http://localhost:80/api/classes

### SRD CLASS BY ID
http://localhost:80/api/classes/10

### SRD FEAT LIST (QUERY OPTIONAL)
http://localhost:80/api/feats?class=fighter&subclass=eldritch+knight&level=10

### SRD FEAT BY ID
http://localhost:80/api/feats/5

### GET CHARACTER
GET http://localhost:80/api/data/pc/1

### GET ALL CHARACTERS
GET http://localhost:80/api/data/pc

### DELETE CHARACTER
DELETE http://localhost:80/api/data/pc/4

### UPSERT CHARACTER
POST http://localhost:80/api/data/pc?uid=kDBRAhqohWPymd7249ZiQ4i9T153
Content-Type: application/json
Authorization: dev wkgreen13@gmail.com

{
  "name": "Carrion",
  "authUsers": ["kDBRAhqohWPymd7249ZiQ4i9T153"],
  "raceID": 1,
  "classID": 5,
  "backgroundID": 5,
  "stats": {
  "str": 10,
    "dex": 15,
    "con": 13,
    "int": 13,
    "wis": 8,
    "cha": 16
  },
  "xp": 300,
  "hp": 8,
  "maxHP": 8,
  "proTools": [
    "Poisoner's Tools"
  ],
  "proWeapons": [
    "Dagger",
    "Dart",
    "Sling",
    "Quarterstaff",
    "Crossbow, light"
  ],
  "languages": [
    "Common",
    "Infernal",
    "Orc",
    "Draconic"
  ],
  "equipmentIDs": [
    31
  ],
  "weaponIDs": [
    17,
    37
  ],
  "inventoryIDs": [
    15
  ],
  "gold": 10,
  "spellIDs": [
    46,
    37
  ]
}