# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  deploy:
    docker:
      # specify the version
      - image: golang
    working_directory: ~/wizardsBrew
    steps:
      - checkout
      - run: git config --global user.email "wkgreen13@gmail.com"
      - run: git config --global user.name "CircleCI"
      - run: cd .. && git clone git@github.com:kjintroverted/wizardsDeploy.git build
      - run: go build .
      - run: mv wizardsBrew ../build
      - run: cd ../build && git add .
      - run: cd ../build && git commit -m "CI deploy"
      - run: cd ../build && git push

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
